/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package oop;

import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import oop.datas.DataManager;
import oop.entities.Durable;
import oop.exceptions.ErrorException;

/**
 *
 * @author kucik
 */
class DurableProductEditorDialog extends javax.swing.JDialog {

    private enum EditType {
        ADD, CHANGE;
    }

    private final DataManager<Durable> manager;
    private List<Durable> products;
    private EditType type;
    private Durable product;

    
    public DurableProductEditorDialog(Durable durable, DataManager<Durable> manager,
            List<Durable> products) {
        initComponents();
        this.manager = manager;
        this.products = products;
        this.product = durable;
        type = EditType.ADD;
        if (durable != null) {
            durableNotNullExecution(durable);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        articleNumberText = new javax.swing.JLabel();
        articleNumberTextAnswer = new javax.swing.JTextField();
        nameTextAnswer = new javax.swing.JTextField();
        nameText = new javax.swing.JLabel();
        brandTextAnswer = new javax.swing.JTextField();
        brandText = new javax.swing.JLabel();
        familyTextAnswer = new javax.swing.JTextField();
        familyText = new javax.swing.JLabel();
        nettoPriceTextAnswer = new javax.swing.JTextField();
        nettoPriceText = new javax.swing.JLabel();
        warantyPeriodTextAnswer = new javax.swing.JTextField();
        warantyPeriodText = new javax.swing.JLabel();
        cricitalQuantityText = new javax.swing.JLabel();
        criticalQuantityTextAnswer = new javax.swing.JTextField();
        amountUnitsTextAnswer = new javax.swing.JTextField();
        amountUnitsText = new javax.swing.JLabel();
        quantityText = new javax.swing.JLabel();
        quantityTextAnswer = new javax.swing.JTextField();
        taxTextAnswer = new javax.swing.JTextField();
        taxText = new javax.swing.JLabel();
        grossWeightTextAnswer = new javax.swing.JTextField();
        grossWeightText = new javax.swing.JLabel();
        saveBt = new javax.swing.JButton();
        closeBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        articleNumberText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        articleNumberText.setText("Article Number");

        articleNumberTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        nameTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        nameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameText.setText("Name");

        brandTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        brandText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        brandText.setText("Brand");

        familyTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        familyText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        familyText.setText("Family");

        nettoPriceTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        nettoPriceText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nettoPriceText.setText("Netto Price");

        warantyPeriodTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        warantyPeriodText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        warantyPeriodText.setText("Waranty Period");

        cricitalQuantityText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cricitalQuantityText.setText("Critical Quantity");

        criticalQuantityTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        amountUnitsTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        amountUnitsText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amountUnitsText.setText("Amount Units");

        quantityText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        quantityText.setText("Quantity");

        quantityTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        taxTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        taxText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taxText.setText("Tax");

        grossWeightTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        grossWeightText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        grossWeightText.setText("Gross Weight");

        saveBt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        saveBt.setText("Save");
        saveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtActionPerformed(evt);
            }
        });

        closeBt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        closeBt.setText("Close");
        closeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(articleNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(articleNumberTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nameTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(brandText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(brandTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(familyText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(familyTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nettoPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nettoPriceTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(taxText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(taxTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quantityTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amountUnitsText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(amountUnitsTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cricitalQuantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(criticalQuantityTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(warantyPeriodText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grossWeightText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grossWeightTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(warantyPeriodTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveBt)
                                .addGap(137, 137, 137)
                                .addComponent(closeBt)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(articleNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(articleNumberTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(familyText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(familyTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nettoPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nettoPriceTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountUnitsText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountUnitsTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cricitalQuantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criticalQuantityTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(warantyPeriodText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warantyPeriodTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grossWeightTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grossWeightText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeBt)
                    .addComponent(saveBt))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtActionPerformed

    private void saveBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtActionPerformed
        try {
            Durable result = createDurableWithAnswers();
            if (type == EditType.ADD) {
                manager.addEntity(result);
                products.add(result);
            } else if (type == EditType.CHANGE) {
                manager.updateEntity(result);
                int index = products.indexOf(product);
                products.set(index, result);
            }
            this.dispose();
        } catch (ErrorException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_saveBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DurableProductEditorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DurableProductEditorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DurableProductEditorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DurableProductEditorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DurableProductEditorDialog dialog = new DurableProductEditorDialog(null, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountUnitsText;
    private javax.swing.JTextField amountUnitsTextAnswer;
    private javax.swing.JLabel articleNumberText;
    private javax.swing.JTextField articleNumberTextAnswer;
    private javax.swing.JLabel brandText;
    private javax.swing.JTextField brandTextAnswer;
    private javax.swing.JButton closeBt;
    private javax.swing.JLabel cricitalQuantityText;
    private javax.swing.JTextField criticalQuantityTextAnswer;
    private javax.swing.JLabel familyText;
    private javax.swing.JTextField familyTextAnswer;
    private javax.swing.JLabel grossWeightText;
    private javax.swing.JTextField grossWeightTextAnswer;
    private javax.swing.JLabel nameText;
    private javax.swing.JTextField nameTextAnswer;
    private javax.swing.JLabel nettoPriceText;
    private javax.swing.JTextField nettoPriceTextAnswer;
    private javax.swing.JLabel quantityText;
    private javax.swing.JTextField quantityTextAnswer;
    private javax.swing.JButton saveBt;
    private javax.swing.JLabel taxText;
    private javax.swing.JTextField taxTextAnswer;
    private javax.swing.JLabel warantyPeriodText;
    private javax.swing.JTextField warantyPeriodTextAnswer;
    // End of variables declaration//GEN-END:variables

    private void fillTextBoxes(Durable durable) {
        String netto = String.valueOf(durable.getNettoPrice());
        String tax = String.valueOf(durable.getTaxId());
        String quantity = String.valueOf(durable.getQuantity());
        String criticalQuantity = String.valueOf(durable.getCriticalQuantity());
        String warantyPeriod = String.valueOf(durable.getWarantyPeriod());
        String grossWeight = String.valueOf(durable.getGrossWeight());

        articleNumberTextAnswer.setText(durable.getId());
        nameTextAnswer.setText(durable.getName());
        brandTextAnswer.setText(durable.getBrand());
        familyTextAnswer.setText(durable.getFamily());
        nettoPriceTextAnswer.setText(netto);
        taxTextAnswer.setText(tax);
        quantityTextAnswer.setText(quantity);
        criticalQuantityTextAnswer.setText(criticalQuantity);
        amountUnitsTextAnswer.setText(durable.getAmountUnits());
        warantyPeriodTextAnswer.setText(warantyPeriod);
        grossWeightTextAnswer.setText(grossWeight);
    }

    private Durable createDurableWithAnswers() {
        String articleNumber = articleNumberTextAnswer.getText();
        String name = nameTextAnswer.getText();
        String brand = brandTextAnswer.getText();
        String family = familyTextAnswer.getText();
        int nettoPrice = Integer.parseInt(nettoPriceTextAnswer.getText());
        int taxId = Integer.parseInt(taxTextAnswer.getText());
        int quantity = Integer.parseInt(quantityTextAnswer.getText());
        int criticalQuantity = Integer.parseInt(criticalQuantityTextAnswer.getText());
        String amountUnits = amountUnitsTextAnswer.getText();
        int warantyPeriod = Integer.parseInt(warantyPeriodTextAnswer.getText());
        String grossWeightTxt = grossWeightTextAnswer.getText();
        double grossWeightDouble = Double.parseDouble(grossWeightTxt);
        BigDecimal grossWeight = BigDecimal.valueOf(grossWeightDouble);
        Durable result = new Durable(articleNumber, name, brand, family, nettoPrice,
                taxId, quantity, criticalQuantity, amountUnits, warantyPeriod, grossWeight);
        return result;
    }

    private void durableNotNullExecution(Durable durable) {
        fillTextBoxes(durable);
        type = EditType.CHANGE;
        articleNumberTextAnswer.setEditable(false);
    }

}
