package oop;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import oop.datas.DataManager;
import oop.datas.DataManagerFactory;
import oop.entities.Durable;
import oop.entities.Entity;
import oop.entities.Perishable;
import oop.entities.Product;
import oop.entities.Tax;
import oop.logs.Logger;
import oop.types.DataManagerType;

/**
 *
 * @author --G--
 */
public class MainForm extends javax.swing.JFrame {

    private final Map<DataManagerType, DataManager<? extends Entity>> datamanagers;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        datamanagers = fillDataManagers();
        belowCriticalQuantityExecution();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        durableProductsBt = new javax.swing.JButton();
        perishableProductsBt = new javax.swing.JButton();
        taxBt = new javax.swing.JButton();
        exitBt = new javax.swing.JButton();
        saveLogsBt = new javax.swing.JButton();
        welcomeText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        durableProductsBt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        durableProductsBt.setText("Durable Products");
        durableProductsBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durableProductsBtActionPerformed(evt);
            }
        });

        perishableProductsBt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        perishableProductsBt.setText("Perishable Products");
        perishableProductsBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perishableProductsBtActionPerformed(evt);
            }
        });

        taxBt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taxBt.setText("Taxes");
        taxBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxBtActionPerformed(evt);
            }
        });

        exitBt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exitBt.setText("Exit");
        exitBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtActionPerformed(evt);
            }
        });

        saveLogsBt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        saveLogsBt.setText("Save Logs");
        saveLogsBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveLogsBtActionPerformed(evt);
            }
        });

        welcomeText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        welcomeText.setText("Welcome to the Storage Program!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(durableProductsBt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(perishableProductsBt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(exitBt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(saveLogsBt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(taxBt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 78, Short.MAX_VALUE)
                .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(welcomeText)
                .addGap(67, 67, 67)
                .addComponent(durableProductsBt)
                .addGap(44, 44, 44)
                .addComponent(perishableProductsBt)
                .addGap(33, 33, 33)
                .addComponent(taxBt)
                .addGap(30, 30, 30)
                .addComponent(saveLogsBt)
                .addGap(32, 32, 32)
                .addComponent(exitBt)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void durableProductsBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durableProductsBtActionPerformed
        DurableProductsDialog dialog = new DurableProductsDialog(
                (DataManager<Durable>) datamanagers.get(DataManagerType.DURABLE_MANAGER));
        dialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dialog.setModal(true);
        dialog.setVisible(true);
    }//GEN-LAST:event_durableProductsBtActionPerformed

    private void perishableProductsBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perishableProductsBtActionPerformed
        PerishableProductsDialog dialog = new PerishableProductsDialog(
                (DataManager<Perishable>) datamanagers.get(DataManagerType.PERISHABLE_MANAGER));
        dialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dialog.setModal(true);
        dialog.setVisible(true);
    }//GEN-LAST:event_perishableProductsBtActionPerformed

    private void taxBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxBtActionPerformed
        TaxProductsDialog dialog = new TaxProductsDialog(
                (DataManager<Tax>) datamanagers.get(DataManagerType.TAX_MANAGER));
        dialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dialog.setModal(true);
        dialog.setVisible(true);
    }//GEN-LAST:event_taxBtActionPerformed

    private void exitBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtActionPerformed

    private void saveLogsBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveLogsBtActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fileChooser.showSaveDialog(this);
        String path;
        if (result == JFileChooser.APPROVE_OPTION) {
            path = fileChooser.getSelectedFile().getAbsolutePath();
            Logger.saveLogsToPath(path);
        }

    }//GEN-LAST:event_saveLogsBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                    getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton durableProductsBt;
    private javax.swing.JButton exitBt;
    private javax.swing.JButton perishableProductsBt;
    private javax.swing.JButton saveLogsBt;
    private javax.swing.JButton taxBt;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables

    private Map<DataManagerType, DataManager<? extends Entity>> fillDataManagers() {
        Map<DataManagerType, DataManager<? extends Entity>> result = new HashMap<>();
        result.put(DataManagerType.DURABLE_MANAGER, DataManagerFactory.createDataManager(DataManagerType.DURABLE_MANAGER));
        result.put(DataManagerType.PERISHABLE_MANAGER, DataManagerFactory.createDataManager(DataManagerType.PERISHABLE_MANAGER));
        result.put(DataManagerType.TAX_MANAGER, DataManagerFactory.createDataManager(DataManagerType.TAX_MANAGER));
        return result;
    }

    private void belowCriticalQuantityExecution() {
        String message = "";
        DataManager<? extends Entity> manager = datamanagers.get(DataManagerType.DURABLE_MANAGER);
        message += returnMessageIfHaveBelowCriticalQuantity(manager, "Durable; ");
        manager = datamanagers.get(DataManagerType.PERISHABLE_MANAGER);
        message += returnMessageIfHaveBelowCriticalQuantity(manager, "Perishable; ");
        if (message.length() > 0) {
            JOptionPane.showMessageDialog(null, "Have below critical quantity: " + message);
        }
    }

    private String returnMessageIfHaveBelowCriticalQuantity(DataManager<? extends Entity> manager, String message) {
        String result = "";
        List<Product> entities = (List<Product>) manager.getList();
        List<Product> utilList = (List<Product>) manager.getProductsBelowCriticalQuantity(entities);
        if (!utilList.isEmpty()) {
            result += message;
        }
        return result;
    }
}
