/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package oop;

import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import oop.datas.DataManager;
import oop.entities.Perishable;
import oop.exceptions.ErrorException;
import oop.utils.Util;

/**
 *
 * @author kucik
 */
class PerishableProductEditorDialog extends javax.swing.JDialog {

    private enum EditType {
        ADD, CHANGE;
    }

    private final DataManager<Perishable> manager;
    private List<Perishable> products;
    private EditType type;
    private Perishable product;

    /**
     * Creates new form PerishableProductsEditorDialog
     */
    public PerishableProductEditorDialog(Perishable perishable, DataManager<Perishable> manager,
            List<Perishable> products) {
        initComponents();
        this.manager = manager;
        this.products = products;
        this.product = perishable;
        type = EditType.ADD;
        if (perishable != null) {
            perishableNotNullExecution(perishable);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brandTextAnswer = new javax.swing.JTextField();
        amountUnitsText = new javax.swing.JLabel();
        brandText = new javax.swing.JLabel();
        quantityText = new javax.swing.JLabel();
        familyTextAnswer = new javax.swing.JTextField();
        quantityTextAnswer = new javax.swing.JTextField();
        familyText = new javax.swing.JLabel();
        taxTextAnswer = new javax.swing.JTextField();
        nettoPriceTextAnswer = new javax.swing.JTextField();
        taxText = new javax.swing.JLabel();
        nettoPriceText = new javax.swing.JLabel();
        productionDateTextAnswer = new javax.swing.JTextField();
        expirationDateTextAnswer = new javax.swing.JTextField();
        articleNumberText = new javax.swing.JLabel();
        productionDateText = new javax.swing.JLabel();
        expirationDateText = new javax.swing.JLabel();
        saveBt = new javax.swing.JButton();
        articleNumberTextAnswer = new javax.swing.JTextField();
        cricitalQuantityText = new javax.swing.JLabel();
        closeBt = new javax.swing.JButton();
        nameTextAnswer = new javax.swing.JTextField();
        criticalQuantityTextAnswer = new javax.swing.JTextField();
        nameText = new javax.swing.JLabel();
        amountUnitsTextAnswer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        brandTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        amountUnitsText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amountUnitsText.setText("Amount Units");

        brandText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        brandText.setText("Brand");

        quantityText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        quantityText.setText("Quantity");

        familyTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        quantityTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        familyText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        familyText.setText("Family");

        taxTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        nettoPriceTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        taxText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taxText.setText("Tax");

        nettoPriceText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nettoPriceText.setText("Netto Price");

        productionDateTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        expirationDateTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        articleNumberText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        articleNumberText.setText("Article Number");

        productionDateText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productionDateText.setText("Production Date");

        expirationDateText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        expirationDateText.setText("Expiration Date");

        saveBt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        saveBt.setText("Save");
        saveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtActionPerformed(evt);
            }
        });

        articleNumberTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cricitalQuantityText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cricitalQuantityText.setText("Critical Quantity");

        closeBt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        closeBt.setText("Close");
        closeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtActionPerformed(evt);
            }
        });

        nameTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        criticalQuantityTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        nameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameText.setText("Name");

        amountUnitsTextAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(articleNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(articleNumberTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nameTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(brandText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(brandTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(familyText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(familyTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nettoPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nettoPriceTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(taxText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(taxTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quantityTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amountUnitsText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(amountUnitsTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cricitalQuantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(criticalQuantityTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expirationDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productionDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productionDateTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expirationDateTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveBt)
                                .addGap(137, 137, 137)
                                .addComponent(closeBt)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(articleNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(articleNumberTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(familyText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(familyTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nettoPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nettoPriceTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountUnitsText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountUnitsTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cricitalQuantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criticalQuantityTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expirationDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expirationDateTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productionDateTextAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productionDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeBt)
                    .addComponent(saveBt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtActionPerformed
        try {
            Perishable result = createPerishableWithAnswers();
            if (type == EditType.ADD) {
                manager.addEntity(result);
                products.add(result);
            } else if (type == EditType.CHANGE) {
                manager.updateEntity(result);
                int index = products.indexOf(product);
                products.set(index, result);
            }
            this.dispose();
        } catch (ErrorException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_saveBtActionPerformed

    private void closeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerishableProductEditorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerishableProductEditorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerishableProductEditorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerishableProductEditorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PerishableProductEditorDialog dialog = new PerishableProductEditorDialog(null, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountUnitsText;
    private javax.swing.JTextField amountUnitsTextAnswer;
    private javax.swing.JLabel articleNumberText;
    private javax.swing.JTextField articleNumberTextAnswer;
    private javax.swing.JLabel brandText;
    private javax.swing.JTextField brandTextAnswer;
    private javax.swing.JButton closeBt;
    private javax.swing.JLabel cricitalQuantityText;
    private javax.swing.JTextField criticalQuantityTextAnswer;
    private javax.swing.JLabel expirationDateText;
    private javax.swing.JTextField expirationDateTextAnswer;
    private javax.swing.JLabel familyText;
    private javax.swing.JTextField familyTextAnswer;
    private javax.swing.JLabel nameText;
    private javax.swing.JTextField nameTextAnswer;
    private javax.swing.JLabel nettoPriceText;
    private javax.swing.JTextField nettoPriceTextAnswer;
    private javax.swing.JLabel productionDateText;
    private javax.swing.JTextField productionDateTextAnswer;
    private javax.swing.JLabel quantityText;
    private javax.swing.JTextField quantityTextAnswer;
    private javax.swing.JButton saveBt;
    private javax.swing.JLabel taxText;
    private javax.swing.JTextField taxTextAnswer;
    // End of variables declaration//GEN-END:variables

    private void fillTextBoxes(Perishable perishable) {
        String netto = String.valueOf(perishable.getNettoPrice());
        String tax = String.valueOf(perishable.getTaxId());
        String quantity = String.valueOf(perishable.getQuantity());
        String criticalQuantity = String.valueOf(perishable.getCriticalQuantity());
        String expirationDate = Util.dateToString(perishable.getExpirationDate());
        String productionDate = Util.dateToString(perishable.getProductionDate());

        articleNumberTextAnswer.setText(perishable.getId());
        nameTextAnswer.setText(perishable.getName());
        brandTextAnswer.setText(perishable.getBrand());
        familyTextAnswer.setText(perishable.getFamily());
        nettoPriceTextAnswer.setText(netto);
        taxTextAnswer.setText(tax);
        quantityTextAnswer.setText(quantity);
        criticalQuantityTextAnswer.setText(criticalQuantity);
        amountUnitsTextAnswer.setText(perishable.getAmountUnits());
        expirationDateTextAnswer.setText(expirationDate);
        productionDateTextAnswer.setText(productionDate);
    }

    private Perishable createPerishableWithAnswers() {
        String articleNumber = articleNumberTextAnswer.getText();
        String name = nameTextAnswer.getText();
        String brand = brandTextAnswer.getText();
        String family = familyTextAnswer.getText();
        int nettoPrice = Integer.parseInt(nettoPriceTextAnswer.getText());
        int taxId = Integer.parseInt(taxTextAnswer.getText());
        int quantity = Integer.parseInt(quantityTextAnswer.getText());
        int criticalQuantity = Integer.parseInt(criticalQuantityTextAnswer.getText());
        String amountUnits = amountUnitsTextAnswer.getText();
        LocalDate expirationDate = Util.textToDate(expirationDateTextAnswer.getText());
        LocalDate productionDate = Util.textToDate(productionDateTextAnswer.getText());

        Perishable result = new Perishable(articleNumber, name, brand, family, nettoPrice,
                taxId, quantity, criticalQuantity, amountUnits, expirationDate, productionDate);
        return result;
    }

    private void perishableNotNullExecution(Perishable perishable) {
        fillTextBoxes(perishable);
        type = EditType.CHANGE;
        articleNumberTextAnswer.setEditable(false);
    }

}
